title: Erfan Kefayat
email: erfan.kefayat@uncc.edu
description: >-
  Academic and technical portfolio of Erfan Kefayat, focusing on geospatial data
  science, urban systems, spatialâ€“temporal modeling, and AI-driven automation of
  local government workflows.

baseurl: ""
url: "https://erfan-kefayat.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - research.md
  - projects.md
  - publications.md
  - cv.md
  - contact.md
